language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  app: tranquil-savannah-03345
  api_key:
    secure: VtLq3i674ZEMNzx493WUNSYXz/VffCeY6NV0I1jbkSp12GvEXWgH2fPyp93580cTsHi3ixg6T0+mUTFeGqBNaMGHyMMSOU65bwkAGimMIRYRxhpvM0lPCnppW8H/+XSA+WHsDaAvuf65ikx7O8B0Kz7wgCBbE+ht+vAIOMg8JIJZRayXrJZr31waLpG6SHrezozasJjkp+JYQtRm4/12Cpf7227/NS9pVPxHt+BIAHGzuBtvo/SO+ncCrta3ulz7MxdsnIDdcsZNuJ7IlWUgxj6zwmAwQ7Pt30epc6JlZfHzoA6iYiCxfqqIocI0IGX3tzm0SxHuMOeLkh7IzhLDhbblS9FLwEtK01yK6UxPQPxfR9c9q9nb85AKmAFpCfV+R3RNhip3/WNO3BLMCRnooLZ3VGnFfQX5sCjsK7kb7YfR32W8qV0MjR0HUX2q0lJ2zqKD9n0vwrtUcnLsN89WOHz/vBEaQAGNpX9tnQCAXoLWSZ9+u8IKPFbtxq17JopnI00OPI/dYs9hO1aghYbvtHKIvPNs8TWKBrbyxAqJNOlqCQwrAI7OCG1mnpA/KL0zmMM4GBagllQeNzp+/ZlxdTd2Aa3VVQbC9DwZrEiJTQEQe0IfjpA6ThlGAdCNzDedG+zuE4mE6R0JENXqnexNNsOe5sLnIgIBa+cs2ESEf+8=
